#!/bin/sh
#
# http://www.cita.utoronto.ca/~shirokov/soft/ssh-agent
#
# Checks authentication environment.
# If the ssh-agent is not running, starts a new one.
#

SSH_ENV=$HOME/.ssh/env-$HOSTNAME

# Initialize new agent and add authentication
start_agent() {

    # Start authenticating daemon
    # No authentications set up yet, just starting daemon!
    ssh-agent -t 1d | head -2 > ${SSH_ENV}
    chmod 600 ${SSH_ENV}

    # Find SSH_AUTH_SOCK and SSH_AGENT_PID of the available daemon
    . ${SSH_ENV} > /dev/null
}

if [ -z "$SSH_AUTH_SOCK" ] || [ ! -S "$SSH_AUTH_SOCK" ] || [ -z "$SSH_AGENT_PID" ]; then

  if [ -f "$SSH_ENV" ]; then
      # Find SSH_AUTH_SOCK and SSH_AGENT_PID of the available daemon
      . ${SSH_ENV} > /dev/null

      # Check if the agent is still running
      ierr=0
      ps ${SSH_AGENT_PID} > /dev/null || ierr=1

      if [ $ierr == "0" ]; then
        echo > /dev/null
      else
        # If not initialize new agent and
        # add authentication
        start_agent
      fi
  else
      start_agent
  fi

fi

unset start_agent
