tap "homebrew/bundle"

brew "bash"
brew "bash-completion@2"
brew "bat"
brew "bkt"
brew "coreutils"
brew "diff-so-fancy"
brew "entr"
brew "fortune"
brew "node"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "jq"
brew "less"
brew "lesspipe"
brew "lftp"
brew "mas"
brew "moreutils"
brew "neovim"
brew "netcat"
brew "noti"
brew "nyancat"
brew "tmux"
brew "pstree"
brew "python"
brew "rbenv"
brew "ranger"
brew "ripgrep"
brew "ruby-install"
brew "ssh-copy-id", link: true
brew "thefuck"
brew "tig"
brew "tldr"
brew "tmuxinator"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "yarn"
brew "yq"
brew "z"

cask "alacritty"
cask "bettertouchtool"
cask "cryptomator"
cask "devdocs"
cask "font-droid-sans-mono-nerd-font"
cask "ferdium"
cask "karabiner-elements"
cask "keepingyouawake"
cask "keyboardcleantool"
cask "numi"
cask "omnidisksweeper"
cask "stats"
cask "vimr"
cask "visual-studio-code"
cask "vivaldi"
cask "workflowy"

# Latest isn't available for ARM, instead:
#   git clone https://github.com/ytmdesktop/ytmdesktop ~/Code/ytmdesktop
#   cd ~/Code/ytmdesktop/
#   yarn install
#   yarn make --arch arm64
#   sudo unzip 'out/make/zip/darwin/arm64/YouTube Music Desktop App-darwin-arm64-2.0.5.zip' -d /Applications
# cask "ytmdesktop-youtube-music"

mas "Monosnap", id: 540348655
mas "Hour - World Clock", id: 569089415
